# Use version 2 of CircleCI
version: 2

jobs:
  
  # Define a deploy job
  setup_build_deploy:
  
    # Deploy with the Latest Node Docker Image
    docker:
      - image: circleci/node:latest
      
    steps:
    
      # Add the SSH Keys from the Project Settings
      - add_ssh_keys
      
      # Checkout the code from the repository
      - checkout              
      
      # Resolve the SSH Keys
      - run:
          name: Resolve Keys
          command: ssh-keyscan -H 10.137.0.159 >> ~/.ssh/known_hosts
          
      # Install rSync
      - run: 
            name: rSync Install
            command: sudo apt install -y rsync
      
      # Deploy the retrieve repository files to the VM via rSync SSH...
      - run: 
            name: Deploy Project Files
            command: rsync --exclude='.git/' --exclude='README.md' -e ssh -avvz ~/home/ launch launch@10.137.0.159
                #if [ "${CIRCLE_BRANCH}" = "master" ]; then
                      #rsync ssh command
                #else
                      #echo "not master branch."
                #fi
      
workflows:

  # Use version 2 of CircleCI
  version: 2
  easy-deploy:
    jobs:
      - setup_build_deploy